name: "nextblog"

services:
  redis:
    image: redis
    container_name: redis-metapress
    restart: unless-stopped
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres-metapress
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
